# Generated by Django 4.2.8 on 2024-01-15 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drinks", old_name="drink", new_name="drink_name",
        ),
    ]
